/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime false` (hash: 19571d84c8201b24b208939a27c49c22)
interface __BaseEnv_Env {
	CURATION_KV: KVNamespace;
	SPECTRA_ADMIN_PASSWORD: string;
	SPECTRA_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SPECTRA_ADMIN_PASSWORD" | "SPECTRA_SESSION_SECRET">> {}
}
